import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/detailssingleitem">DetailsSingleItem</Link>
        </li>
        <li>
          <Link to="/detailsmultiitem">DetailsMultiItem</Link>
        </li>
        <li>
          <Link to="/detailsitemsbid">DetailsItemsBid</Link>
        </li>
        <li>
          <Link to="/attributes">Attributes</Link>
        </li>
        <li>
          <Link to="/info">Info</Link>
        </li>
        <li>
          <Link to="/unverifiedyet">Unverifiedyet</Link>
        </li>
        <li>
          <Link to="/hover">Hover</Link>
        </li>
        <li>
          <Link to="/verifyaddress">VerifyAddress</Link>
        </li>
        <li>
          <Link to="/confirmterms">ConfirmTerms</Link>
        </li>
        <li>
          <Link to="/bid">Bid</Link>
        </li>
        <li>
          <Link to="/typing">Typing</Link>
        </li>
        <li>
          <Link to="/successone">SuccessOne</Link>
        </li>
        <li>
          <Link to="/detailsitemsbidone">DetailsItemsBidOne</Link>
        </li>
        <li>
          <Link to="/detailsbidmore">DetailsBidMore</Link>
        </li>
        <li>
          <Link to="/detailsinfo">DetailsInfo</Link>
        </li>
        <li>
          <Link to="/bidmore">BidMore</Link>
        </li>
        <li>
          <Link to="/success">Success</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
